# TPM_REPO := ${HOME}/.tmux/plugins

# .PHONY: init
# init: ${TPM_REPO}
# 	ln -svf ${PWD}/tmux.conf ${HOME}/.tmux.conf

# .PHONY: set
# set: init

# ${TPM_REPO}:
# 	mkdir -p ${TPM_REPO} && \
# 	git clone https://github.com/tmux-plugins/tpm ${TPM_REPO}/tpm; \

# .PHONY: clean
# clean:
# 	rm -rf ${TPM_REPO} || true && \
# 	unlink ${HOME}/.tmux.conf || true